### ISSUE TITLE
Suffix not working with other plugins when set to suffix: ''

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#1]
Config: http://pastebin.com/N4fbZCV2
Latest Log: http://pastebin.com/JJVcTX4X
Plugin List: https://gyazo.com/a5f7a4bbc367e2e1ab860e566117b96d

**Comment by Firestar311** [comment]
Hello, as I mentioned before on the thread, please edit your config.yml to have the suffix: '' on your default group. And if you are referring to PEX as your suffix plugin mentioned in the thread, I am aware of that fact. I am working on a new version that allows multiple suffixes and a way to get the prefixes/suffixes from the permissoins plugin.

**Comment by WitherSkeletons** [comment]
Just a FYI I was using pex as an example I am using tags through another plugin

**Comment by Firestar311** [comment]
Looking at your plugin list, PEX is the only one that I see that has suffixes. May I ask what the name of the plugin is that is setting suffixes?

**Comment by WitherSkeletons** [comment]
I haven't 100% decided on a tags plugin yet

**Comment by WitherSkeletons** [comment]
https://dev.bukkit.org/bukkit-plugins/vtags/ This is the plugin I will be using

**Comment by Firestar311** [comment]
Looking at the vTags plugin, I cannot add support for it due to the fact that there is no API for me to hook into.

**Comment by WitherSkeletons** [comment]
Will you at least be able to fix it so all other suffix plugins will override MultiPrefix if there is no suffix set?

**Comment by Firestar311** [comment]
I will be adding support for Permissions plugins (PEX and GroupManager through Vault) for multiple suffixes.

**Comment by WitherSkeletons** [comment]
Would it be possible for the developer of the Tags plugin to have it hook into Vault so it will work with MultiPrefix?

**Comment by WitherSkeletons** [comment]
When will the hook be done just out of curiosity? Also ignore the above message I asked the dev to hook it into pex

**Comment by WitherSkeletons** [comment]
Support for pex not hook*

**Comment by Firestar311** [comment]
I have to rework the entire plugin again :( My fault. I will be done soon, as I am job searching most of my days are spent doing that.

**Comment by WitherSkeletons** [comment]
Alright sounds good. Also good luck with your job hunt

**Comment by Firestar311** [comment]
This bug has now been fixed, Permissions Plugin support now implemented (Groupmanager and PEX). Essentials nickname support added and multisuffix now enabled
