### ISSUE TITLE
& in chat issue

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#2]
If you type & in chat in the middle of a message it will reset the players chat color(set in the chat format section before the message variable)

**Comment by Firestar311** [comment]
Issue has been fixed in commit [c037f50](https://github.com/Firestar311/MultiPrefix/commit/c037f50bf2e93a7706fe84e777909d15170aa90a)
Update **2.0.1** on BukkitDev page is awaiting approval
