### ISSUE TITLE
Permission Suffixes

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#3]
Could you change permission suffixes from using the world to using the global suffix?

**Comment by WitherSkeletons** [comment]
Also the plugin appears to not be loading on startup but works when I load it in via a plugin loader

**Comment by Firestar311** [comment]
Hello, due to how Vault is setup, I must do that, I might have to look into direct PEX support, or see if there is another way. 

Can you post your server latest.log file via pastebin.com so that I can find out why it is not.

**Comment by WitherSkeletons** [comment]
I'm partially confused.. So is there a way for me to make it display as a global suffix or would that require you hooking directly into PermissionsEx? I'll get the long to you later this evening as I am not home right now

**Comment by Firestar311** [comment]
If you have PEX or your permissions plugin setup to not have a per world suffix option, it will use the global suffix that is set.

**Comment by WitherSkeletons** [comment]
How would I go about doing that as there isn't an option in the config.yml. Sorry if I seem stupid I'm usually good at this. There are no per world suffix options in my permissions.yml

**Comment by Firestar311** [comment]
Did you regenerate your config.yml?
If not, copy/paste your current group settings (I did not change how that works) and delete the current one. If you did, just put the name of your main world in the world: option in the config

**Comment by WitherSkeletons** [comment]
Oh my bad I thought you were talking about PermissionsEx

**Comment by WitherSkeletons** [comment]
Also I'm not sure if this is a bug on your side or if there is a way to change this with essentials but it displays prefix characters for some things e.x: https://gyazo.com/611c706cfd340227aa96c29266f1647a

I can't send the whole log but as MultiPrefix tries to load in before anything here is the log until the next plugin is enabled http://pastebin.com/0h9AnFgY

**Comment by Firestar311** [comment]
Can you provide me with your config.yml and also tell me which version of Essentials you are using?

**Comment by WitherSkeletons** [comment]
Essentials 2.0.1-b413 (EssentialsX)
Config.yml(Essentials): http://hastebin.com/yuretipaco.coffee
Config.yml(MultiPrefix): http://hastebin.com/fegiluxucu.vbs

Other: I have my main world set to world in server.properties and world in MultiPrefix set to world. Global suffixes still do not appear to be working

**Comment by Firestar311** [comment]
I found out the problem with the not loading. And I am working on the fix for it. And did you disable in essentials what my config.yml told you to disable in Essentials?

**Comment by Firestar311** [comment]
Fixed in the next version, waiting on BukkitDev approval
New version: **2.1.1**
