### ISSUE TITLE
Chat issue reoccuring

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#4]
The chat issue mentioned in issue #3 is reoccurring in other plugins such as WorldGuard and other places in essentials as well.

**Comment by WitherSkeletons** [comment]
Also, I have everything set to world and the suffixes set directly under options without a world in PermissionsEx are still not showing

**Comment by Firestar311** [comment]
Can you please provide screenshots of the issues?

**Comment by WitherSkeletons** [comment]
https://gyazo.com/b45c08d82ec4ac2fd28b75d7bc13379a

**Comment by WitherSkeletons** [comment]
Is there a way you could get the suffixes working globally through permissionsex working soon?

**Comment by Firestar311** [comment]
Ok fixed the chat issues and due to how PermissionsEx is setup I cannot have it global, it will automatically use a global suffix if there are no per-world suffixes set.
