### ISSUE TITLE
Permission Prefixes and Permission Suffixes not working

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#5]
Hello,
I've finally realized after a really long time that I must've confused you with permission suffixes. Could you change permission suffixes so it reads the player information for the suffix instead of the group(or both which ever is easier)? Sorry about the confusion early on

**Comment by WitherSkeletons** [comment]
Also on a side note everytime a permission suffix is updated currently it requires MultiPrefix to reload. Could this be changed?

**Comment by Firestar311** [comment]
Hey, sorry, I saw the notification then forgot about this. 
Yes, you really confused me before, so thanks for clearing that up. 
I will add a feature to the plugin that allows suffixes on a per player bases and I will set in the config to have the player's suffixes or groups's suffixes first.

**Comment by WitherSkeletons** [comment]
ok

**Comment by WitherSkeletons** [comment]
any idea when this will be done?

**Comment by Firestar311** [comment]
Hey sorry, I have been sick for the last few days and really haven't been at a computer. I am getting better now, but it will be a few days more before I feel good enough to code. 
Sorry

**Comment by WitherSkeletons** [comment]
All good, personal health is way more important get well soon

**Comment by Firestar311** [comment]
I just realized that I completely forgot about this issue. I have been relearning Forge Modding and have gotten into a mood with it. I will begin work soon.

**Comment by WitherSkeletons** [comment]
Ok sounds good :)

**Comment by WitherSkeletons** [comment]
Any progress?

**Comment by WitherSkeletons** [comment]
Think you could get this done within the next few days possibly?

**Comment by WitherSkeletons** [comment]
Still working on this?

**Comment by Firestar311** [comment]
Hey sorry, I have been just out of it recently.
My computer has had a few viruses so I do not trust files to be uploaded until I get them all removed

**Comment by Firestar311** [comment]
I have implemented Permissions Suffixes into the version 2.2 of the plugin which is currently awaiting approval on Bukkit.
