### ISSUE TITLE
Addition of player prefixes/suffixes

### ISSUE THREAD

**Issue by WitherSkeletons** [Firestar311/MultiPrefix#6]
Hello,
Could you add in support for player permission prefixes/suffixes?

**Comment by Firestar311** [comment]
Look at my response in #5

**Comment by WitherSkeletons** [comment]
Progress? I really need this update please

**Comment by Firestar311** [comment]
Hey sorry, virus crashed my computer, and I had to do a clean install meaning I lost my progress on the features that you requested. I have to go from what is currently on GitHub, sorry.

**Comment by WitherSkeletons** [comment]
Alright, could you get it done by like next Thursday possibly?

**Comment by Firestar311** [comment]
I have implemented Permissions Suffixes into the version 2.2 of the plugin which is currently awaiting approval on Bukkit.
